### ISSUE TITLE
Nuget API key update required?

### ISSUE THREAD

**Issue by Numpsy** [serilog/serilog-enrichers-process#12]
Looks like the Nuget API key used by the build has expired?

https://ci.appveyor.com/project/serilog/serilog-enrichers-process/builds/27729114

**Comment by Numpsy** [comment]
@nblumhardt Not sure who's responsible for that sort of thing, but fwiw (looking at the build history, looks like the current keys expired last year?

**Comment by nblumhardt** [comment]
Thanks - should be fixed now 👍
