### ISSUE TITLE
Process (& Thread) Enrichers not working with self-contained/publishSingleFile apps

### ISSUE THREAD

**Issue by scissorrunner** [serilog/serilog-enrichers-process#21]
I noticed that the ProcessId and ThreadId properties are blank in the following configuration:
* net6.0-windows 
* PublishSingleFile=true
* Using Serilog.Settings.Configuration and appsettings.json to reference enrichers (not setup in code) via `"Enrich": [ "WithProcessId", "WithThreadId" ],`

The logging works correct (properties are there) if I copy these enricher assemblies into the executable directory (I verified that they are also part of the packaged executable via the sfextract utility, so they weren't "trimmed" out in publishing)

As a workaround, I'm deploying these two again into the installation directory.

Is this a known/expected limitation?

**Comment by nblumhardt** [comment]
https://github.com/serilog/serilog-settings-configuration/#net-50-onwards-single-file-applications

HTH!

**Comment by scissorrunner** [comment]
> https://github.com/serilog/serilog-settings-configuration/#net-50-onwards-single-file-applications
> 
> HTH!

Thanks - that was it!
